// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_CarlosLopez_20190720.DAL;

namespace P2_AP1_CarlosLopez_20190720.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20211108145044_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_CarlosLopez_20190720.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoTarea")
                        .HasColumnType("TEXT");

                    b.HasKey("TipoId");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Requerimiento = "Analizar la opcion de clientes",
                            Tiempo = 120,
                            TipoTarea = "Analisis"
                        },
                        new
                        {
                            TipoId = 2,
                            Requerimiento = "Hacer un diseño excelente",
                            Tiempo = 60,
                            TipoTarea = "Diseño"
                        },
                        new
                        {
                            TipoId = 3,
                            Requerimiento = "Programar todo el registro",
                            Tiempo = 240,
                            TipoTarea = "Programacion"
                        },
                        new
                        {
                            TipoId = 4,
                            Requerimiento = "Probar con mucho cuidado",
                            Tiempo = 30,
                            TipoTarea = "Prueba"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
